/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleTreeWithHistorySol from "./MerkleTreeWithHistory.sol";
export type { merkleTreeWithHistorySol };
import type * as zkTreeSol from "./ZKTree.sol";
export type { zkTreeSol };
export type { Verifier } from "./Verifier";
export type { ZKMapVote } from "./ZKMapVote";
export type { ZKVote } from "./ZKVote";
